// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fripjgpqthrjauwjlkzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaXBqZ3BxdGhyamF1d2psa3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDg4MDYsImV4cCI6MjA3NTY4NDgwNn0.PhcO2ERXkxE3jdh0d9FNLJDdc2hlD8v47E_GxsBt_iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});